const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];
let currentStep = 0;
let lastCleanIps = [];
const titles = ['شروع ساده و مرحله‌ای','ایمیل و Cloudflare','Deploy داخلی BPB','IP Quality Scanner','Subscription و تست','خروجی نهایی'];
function toast(msg){ const t=$('#toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2800); }
function setStep(i){ currentStep=Math.max(0,Math.min(5,i)); $$('.step').forEach((b,idx)=>b.classList.toggle('active',idx===currentStep)); $$('.panel').forEach((p,idx)=>p.classList.toggle('active',idx===currentStep)); $('#pageTitle').textContent=titles[currentStep]; }
async function post(path, body){ const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})}); const data=await res.json(); if(!data.ok){ const err=data?.deploy?.errors?.[0]||data?.token?.errors?.[0]||data?.accounts_raw?.errors?.[0]||{}; throw new Error(data.error||err.help_fa||err.message||'خطای ناشناخته'); } return data; }
function selected(selector){ return $$(selector+':checked').map(x=>x.value); }
function runPayload(){ return {subscription_url:$('#subUrl').value.trim(),timeout:parseInt($('#timeout')?.value||'6',10),workers:parseInt($('#workers')?.value||'32',10),limit:parseInt($('#limit')?.value||'1600',10),random_count:parseInt($('#randomCount')?.value||'0',10),mode:$('input[name="mode"]:checked')?.value||'auto',ip_list:$('#ipList')?.value||'',ports:selected('.port')}; }
function scanPayload(){ return {ip_text:$('#scannerIpText').value||'',cidr_text:$('#scannerCidrText').value||'',random_count:parseInt($('#scanRandomCount').value||'0',10),ip_limit:parseInt($('#ipLimit').value||'900',10),timeout:parseInt($('#scanTimeout').value||'4',10),workers:parseInt($('#scanWorkers').value||'64',10),sni_host:$('#sniHost').value.trim()||'speed.cloudflare.com',ports:selected('.scan-port')}; }
function cfPayload(){ return {api_token:$('#cfToken').value.trim(),account_id:$('#cfAccountId').value.trim(),worker_name:$('#workerName').value.trim()||'bpb-panel',uuid:$('#bpbUuid').value.trim(),sub_path:$('#subPath').value.trim()||'sub',proxy_ip:$('#proxyIp').value.trim()}; }
function prettyCloudflareResult(data){ const lines=[]; lines.push(data.ok?'Deploy موفق بود.':'Deploy کامل نشد.'); if(data.worker_url_hint){ lines.push(''); lines.push('لینک پیشنهادی Subscription:'); lines.push(data.worker_url_hint); $('#subUrl').value=data.worker_url_hint; } if(data.next_steps_fa){ lines.push(''); lines.push('گام‌های بعدی:'); data.next_steps_fa.forEach(x=>lines.push('- '+x)); } const err=data?.deploy?.errors?.[0]||data?.subdomain_enable?.errors?.[0]; if(err){ lines.push(''); lines.push('خطا: '+(err.help_fa||err.message||JSON.stringify(err))); } lines.push(''); lines.push('جزئیات فنی:'); lines.push(JSON.stringify(data,null,2)); return lines.join('\n'); }
function renderTopResults(items){ const box=$('#results'); box.innerHTML=''; if(!items||!items.length) return; items.slice(0,18).forEach((r,idx)=>{ const div=document.createElement('div'); div.className='result-row '+(r.ok?'ok':'fail'); const ping = Number.isFinite(r.latency_ms) ? r.latency_ms+'ms' : '-'; div.innerHTML=`<b>${idx+1}. ${r.ok?'OK':'FAIL'} | ${r.endpoint} | ping ${ping} | score ${r.score}</b><span>${r.message||''}</span>`; box.appendChild(div); }); }
function renderIpScan(data){ const lines=[]; lines.push(`کاندیدها: ${data.candidate_count}`); lines.push(`Endpoint سالم: ${data.working_count}`); lines.push(''); lines.push('بهترین خروجی‌ها:'); (data.top_results||[]).slice(0,30).forEach(r=>lines.push(`${r.ok?'OK':'FAIL'} | ${r.endpoint} | ${r.latency_ms}ms | ${r.message||''}`)); lines.push(''); lines.push(`ذخیره شد: ${data.files?.clean||'output/clean_ips.txt'}`); $('#ipScanResult').textContent=lines.join('\n'); }
$$('.step').forEach((b,i)=>b.addEventListener('click',()=>setStep(i)));
$('#nextBtn').addEventListener('click',()=>setStep(currentStep+1)); $('#prevBtn').addEventListener('click',()=>setStep(currentStep-1));
$('#openOutputBtn').addEventListener('click',()=>fetch('/api/open-output')); $('#openOutputBtn2').addEventListener('click',()=>fetch('/api/open-output')); $('#openIntegratedBtn').addEventListener('click',()=>fetch('/api/open-integrated-folder'));
$$('[data-open-url]').forEach(btn=>btn.addEventListener('click',async()=>{ try{ await post('/api/open-url',{key:btn.dataset.openUrl}); toast('لینک باز شد.'); }catch(e){ toast('باز کردن لینک انجام نشد: '+e.message); } }));
$('#genUuidBtn').addEventListener('click',()=>{ const u=crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&0x3|0x8);return v.toString(16)}); $('#bpbUuid').value=u; toast('UUID ساخته شد.'); });
$('#verifyCfBtn').addEventListener('click',async()=>{ const btn=$('#verifyCfBtn'); btn.disabled=true; $('#cfDeployResult').textContent='درحال بررسی Token…'; try{ const data=await post('/api/cf-verify',cfPayload()); const accounts=data.accounts||[]; $('#cfDeployResult').textContent=`Token معتبر است.\nاکانت‌های پیدا شده:\n${accounts.map(a=>`- ${a.name||'Account'} | ${a.id}`).join('\n')||'هیچ اکانتی برنگشت؛ Account ID را دستی وارد کن.'}`; if(accounts.length&&!$('#cfAccountId').value.trim()) $('#cfAccountId').value=accounts[0].id; toast('Token بررسی شد.'); }catch(e){ $('#cfDeployResult').textContent='خطا: '+e.message; toast('بررسی Token ناموفق بود.'); } finally{ btn.disabled=false; } });
$('#deployCfBtn').addEventListener('click',async()=>{ const btn=$('#deployCfBtn'); btn.disabled=true; $('#cfDeployResult').textContent='درحال Deploy فایل داخلی BPB روی Cloudflare…'; try{ const data=await post('/api/cf-deploy',cfPayload()); $('#cfDeployResult').textContent=prettyCloudflareResult(data); toast('Deploy انجام شد.'); }catch(e){ $('#cfDeployResult').textContent='خطا: '+e.message; toast('Deploy کامل نشد.'); } finally{ btn.disabled=false; } });
$('#pasteBtn').addEventListener('click',async()=>{ try{$('#subUrl').value=await navigator.clipboard.readText(); toast('از Clipboard خوانده شد.');}catch(e){toast('مرورگر اجازه Paste نداد؛ دستی Paste کن.');} });
$('#fetchBtn').addEventListener('click',async()=>{ const btn=$('#fetchBtn'); btn.disabled=true; $('#fetchResult').textContent='درحال دریافت Subscription…'; try{ const data=await post('/api/fetch',runPayload()); $('#fetchResult').textContent=`لینک سالم است.\nکل خطوط دریافتی: ${data.total_lines}\nکانفیگ‌های قابل تست: ${data.supported_configs}\nنمونه‌ها:\n- ${(data.examples||[]).join('\n- ')}\n\nذخیره شد: ${data.saved}`; toast('Subscription دریافت شد.'); }catch(e){ $('#fetchResult').textContent='خطا: '+e.message; toast('خطا در دریافت لینک.'); } finally{ btn.disabled=false; } });
$('#scanIpBtn').addEventListener('click',async()=>{ const btn=$('#scanIpBtn'); btn.disabled=true; btn.textContent='درحال اسکن…'; $('#ipScanResult').textContent='اسکن شروع شد. نتیجه‌ها بر اساس latency و پاسخ TLS/HTTP مرتب می‌شوند…'; try{ const data=await post('/api/scan-ips',scanPayload()); lastCleanIps=data.clean_ips||[]; renderIpScan(data); toast(`${data.working_count} endpoint سالم پیدا شد.`); }catch(e){ $('#ipScanResult').textContent='خطا: '+e.message; toast('اسکن کامل نشد.'); } finally{ btn.disabled=false; btn.textContent='اسکن کیفیت و ذخیره clean_ips.txt'; } });
$('#useCleanIpsBtn').addEventListener('click',()=>{ if(!lastCleanIps.length){ toast('اول اسکن IP را اجرا کن.'); return; } $('#ipList').value=lastCleanIps.join('\n'); const clean=$('input[name="mode"][value="clean_ip"]'); if(clean) clean.checked=true; setStep(4); toast('IPهای سالم منتقل شدند.'); });
$('#runBtn').addEventListener('click',async()=>{ const btn=$('#runBtn'); btn.disabled=true; btn.textContent='درحال تست واقعی‌تر…'; $('#bestConfig').value=''; renderTopResults([]); setStep(5); try{ const data=await post('/api/run',runPayload()); if(data.best){ $('#bestConfig').value=data.best.config||''; } renderTopResults(data.top_results); const phase=data.phase?` (${data.phase})`:''; toast(`تمام شد${phase}. ${data.working_count} کانفیگ OK پیدا شد.`); }catch(e){ $('#bestConfig').value='خطا: '+e.message; toast('اجرا کامل نشد.'); } finally{ btn.disabled=false; btn.textContent='شروع اجرا و ساخت خروجی قابل تست'; } });
$('#copyBestBtn').addEventListener('click',async()=>{ const text=$('#bestConfig').value.trim(); if(!text) return toast('هنوز کانفیگی برای کپی وجود ندارد.'); try{ await navigator.clipboard.writeText(text); toast('کانفیگ کپی شد.'); }catch(e){ toast('کپی خودکار نشد؛ دستی انتخاب و کپی کن.'); } });
setStep(0);
